# Generated by Django 3.2.7 on 2021-09-06 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dinamicformapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formmodel',
            name='data',
            field=models.JSONField(),
        ),
    ]
